# Site settings
title: 旷世的忧伤
subtitle: Huoty's Blog
keywords: huoty, konghy, 旷世的忧伤, 计算机技术, 感悟, Linux, Python, Web
description: Huoty's blog，旷世的忧伤。专注于各类计算机技术，记录所感所想所思。分享 Linux 使用技巧，Python 开发技术，以及其他程序设计经验
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.konghy.cn" # 你的域名
page_no_title: "旷世的忧伤 | Huoty's Blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: Huoty
email: sudohuoty@gmail.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
gems: [jekyll-paginate]

# Pageinate settings
paginate: 10 # 分页大小
paginate_path: ":num"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: //konghy.cn
    icon: icon-about
  - page: 订阅
    directory: feed.xml
    icon: icon-rss

# Link settings
links: # 友情链接
  - title: Jekyll 博客系统
    url: http://jekyllcn.com/
  - title: 多说评论系统
    url: http://duoshuo.com/
  - title: 聚宽量化交易平台
    url: https://www.joinquant.com/
  - title: 卢松松博客
    url: http://lusongsong.com/

# Code hub settings
codehub: # 友情链接
  - title: Github
    url: https://github.com/kuanghy
  - title: Git@OSC
    url: https://git.oschina.net/kuanghy
  - title: Coding
    url: https://coding.net/u/konghy
