# Site settings
title: 旷世的忧伤
subtitle: Huoty's Blog
description: Huoty's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # 你的域名
page_no_title: "旷世的忧伤 | Huoty's Blog" # 文章无标题时默认显示内容
beian: # "备案号"
email: sudohuoty@gmail.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
gems: [jekyll-paginate]

# Pageinate settings
paginate: 10 # 分页大小
paginate_path: ":num"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 历史
    directory: history/
    icon: icon-history
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: //konghy.cn
    icon: icon-about
  - page: 订阅
    directory: feed.xml
    icon: icon-rss

# Link settings
links: # 友情链接
  - title: Jekyll 博客系统
    url: http://jekyllcn.com/
  - title: 多说评论系统
    url: http://duoshuo.com/
  - title: 聚宽量化交易平台
    url: https://www.joinquant.com/
  - title: 卢松松博客
    url: http://lusongsong.com/

# Code hub settings
codehub: # 友情链接
  - title: Github
    url: https://github.com/kuanghy
  - title: Git@OSC
    url: https://git.oschina.net/kuanghy
  - title: Coding
    url: https://coding.net/u/konghy
